---
title: Hannah Cobb
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 
logo: 
teaser: 
locale: en
url: 
feed:
  path: atom.xml
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:categories/:title/"
kramdown:
  toc_levels: 1..2
highlighter: rouge
plugins:
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
owner:
  name: 
  email: 
  twitter: 
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: bio-photo.jpg
  disqus-shortname: 
include:
- ".htaccess"
exclude:
- "*.less"
- "*.sublime-project"
- "*.sublime-workspace"
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- CHANGELOG
- Capfile
- Gemfile
- Gruntfile.js
- LICENSE
- README
- Rakefile
- config
- gulpfile.js
- lib
- log
- node_modules
- package.json
- spec
- tmp
